# Generated by Django 5.1.4 on 2025-02-15 22:22

import create_pdf_cert.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now=True)),
                ('cert', models.FileField(upload_to='create_pdf_cert/certificates/')),
                ('created', models.DateTimeField(auto_now=True)),
                ('cert_number', models.CharField(default=create_pdf_cert.models.generate_cert_number, editable=False, max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Certificates',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='MailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('recipient_email', models.EmailField(default='', max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Mail Settings',
            },
        ),
    ]
