# Generated by Django 5.1.4 on 2025-03-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_pdf_cert', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('cert', models.FileField(upload_to='create_pdf_cert/gift_certificates/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateField()),
                ('cert_number', models.CharField(editable=False, max_length=11, unique=True)),
            ],
        ),
    ]
