# Generated by Django 5.1.4 on 2025-03-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_pdf_cert', '0002_giftcert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cert',
            name='cert',
            field=models.FileField(upload_to='create_pdf_cert/certificates/graduation_certificates'),
        ),
        migrations.AlterField(
            model_name='giftcert',
            name='cert',
            field=models.FileField(upload_to='create_pdf_cert/certificates/gift_certificates'),
        ),
    ]
